version: '3.7'

services:
  defi-blockchain:
    image: defi/defichain:2.6.0
    ports:
      - "19554:19554"
    command: >
      defid
      -printtoconsole
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcuser=api-rpcuser
      -rpcpassword=api-rpcpassword
      -rpcworkqueue=512
      -masternode_operator=mswsMVsyGMj1FzDMbbxw2QW3KvQAv2FKiy
      -regtest=1
      -jellyfish_regtest=1
      -txnotokens=0
      -logtimemicros
      -txindex=1
      -acindex=1
      -amkheight=0
      -bayfrontheight=1
      -bayfrontgardensheight=2
      -clarkequayheight=3
      -dakotaheight=4
      -dakotacrescentheight=5
      -eunosheight=6
      -eunospayaheight=7
      -fortcanningheight=8
      -fortcanningmuseumheight=9
      -fortcanninghillheight=10
  ocean-api:
    build:
      context: .
      args:
        APP: ocean-api
    image: ocean-api:latest
    ports:
      - "3000:3000"
    depends_on:
      - defi-blockchain
    environment:
      - BLOCKCHAIN_CPP_URL=http://api-rpcuser:api-rpcpassword@defi-blockchain:19554
