version: "3.7"

services:
  nanos:
    image: ledgerhq/speculos
    volumes:
      - ./nanos#btc#1.6#29717f9c.elf:/nanos#btc#1.6#29717f9c.elf
    ports:
      - "1234:1234"
      - "40000:40000" # apdu
      - "41000:41000" # vnc
      - "42000:42000" # tcp buttons
    command: "/nanos#btc#1.6#29717f9c.elf --model nanos --sdk 1.6 --seed secret --display headless --apdu-port 40000 --vnc-port 41000 --button-port 42000"
#    command: "--model nanos ./apps/btc.elf --sdk 1.6 --seed secret --display headless --apdu-port 40000 --vnc-port 41000 --button-port 42000"
    # Add `--vnc-password "<password>"` for macos users to use built-in vnc client.

#docker run -it -v "$(pwd)"/apps:/speculos/apps \
  #-p 1234:1234 -p 40000:40000 -p 41000:41000 -p 42000:42000 \
  #ledgerhq/speculos --model nanos ./apps/btc.elf --sdk 1.6 --seed "secret" --display headless \
  #--apdu-port 40000 --vnc-port 41000 --button-port 42000
