# Shift-left testing to mitigation upstream risk
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - run: npm ci
      - run: npm run lerna:build
      - run: npm run format:fail
      - run: npm run lint:fail
      - run: npm run lerna:pack
